import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import getWeb3 from './api/web3'
import { contractAbi, contractAddress } from './api/contractInfo'
import { useEffect, useState } from 'react'

export default function Home() {
  const walletAddress = '0x61b12F6D46412aAe6F857FDF059E3e48D4ecF218'
  let currentWeb3

  const [itemState, setItemState] = useState('');
  const [balanceState, setBalanceState] = useState('');

  useEffect(() => {
    currentWeb3 = getWeb3()
    console.log(currentWeb3)
  }, [])

  // useEffect(() => {
  //   const setInitialBalance = async () => {
  //     let initialBalance = await currentWeb3.eth.getBalance(walletAddress)
  //     initialBalance = currentWeb3.utils.fromWei(initialBalance, 'ether')
  //     setBalanceState(initialBalance)
  //   }
  //   setInitialBalance()
  // }, [])

  const handlePayToGetTool = async () => {
    const playToEarnContract = new currentWeb3.eth.Contract(contractAbi, contractAddress)
    console.log(playToEarnContract)
    await playToEarnContract.methods.PayToGetTool().send({from: walletAddress, value: currentWeb3.utils.toWei('0.01', 'ether')})
    const URI = await playToEarnContract.methods.tokenURI(4).call({from: walletAddress})
    setItemState(URI)
    console.log(URI)
  }

  const handleWorkCompleted = async () => {
    const playToEarnContract = new currentWeb3.eth.Contract(contractAbi, contractAddress)
    console.log(playToEarnContract)
    await playToEarnContract.methods.WorkCompleted().send({from: walletAddress})
    const changedBalance = await currentWeb3.eth.getBalance(walletAddress)
    changedBalance = currentWeb3.utils.fromWei(changedBalance, 'ether')
    setBalanceState(changedBalance)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://ropsten.etherscan.io/address/0xF8676039BB09fbeF81F27286378c4f4FD27e3f95">PlayToEarn!</a>
        </h1>
          <p className={styles.description}>
            残高: {balanceState}
          </p>
        {!!itemState && (
          <p className={styles.description}>
            My Housework Item is {itemState}
          </p>
        )}

        <div className={styles.grid}>
          <a onClick={() => handlePayToGetTool()} className={styles.card}>
            <h2>道具NFTを購入する</h2>
            <p>家事をするために道具を購入しよう</p>
          </a>

          <a onClick={() => handleWorkCompleted()} className={styles.card}>
            <h2>家事完了！</h2>
            <p>家事が完了したら登録してイーサをもらいましょう!</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
